import { writeFileSync } from "node:fs";
import { listManifestAssets } from "../lib/products/image-manifest";

/**
 * Regenerates docs/image-assets.md from the manifest so the licensing register
 * can never drift from the code. Run with: pnpm assets:register
 */

const STATUS_LABEL: Record<string, string> = {
  own: "Business original",
  approved: "Permission granted",
  pending: "Permission not yet granted",
  "not-required": "No permission required",
};

const assets = listManifestAssets().sort((a, b) => a.file.localeCompare(b.file));

const pending = assets.filter((a) => a.permissionStatus === "pending");
const own = assets.filter((a) => a.permissionStatus === "own");
const approved = assets.filter((a) => a.permissionStatus === "approved");

const rows = assets
  .map(
    (a) =>
      `| \`${a.file}\` | ${a.source} | ${STATUS_LABEL[a.permissionStatus]} | ${a.license} | ${a.sourceUrl ? `[link](${a.sourceUrl})` : "—"} |`
  )
  .join("\n");

const content = `# Image assets and licensing register

<!-- Generated by scripts/generate-asset-register.ts. Do not edit by hand. -->

Every externally sourced image is recorded here. An asset marked **Permission
not yet granted** has a reserved path and written alt text, but the file must
not be downloaded or published until written permission exists.

## Summary

| State | Count |
| ----- | ----- |
| Business original | ${own.length} |
| Permission granted | ${approved.length} |
| Permission not yet granted | ${pending.length} |
| **Total reserved assets** | **${assets.length}** |

## Rules the application enforces

- No external image URLs exist in application code. If an asset is not local or
  in Supabase Storage, \`next/image\` fails the build.
- Seed data ships with no photographs, so no stock image is ever presented as a
  specific product's profile, coil, or installation.
- Where no photograph exists, the product renders an SVG cross-section of its
  own profile rather than unrelated imagery.
- Alt text is written per asset here and stored on the \`product_images\` row.
  It is never generated from the filename.

## Register

| File | Source | Permission | License | Reference |
| ---- | ------ | ---------- | ------- | --------- |
${rows}

## Manufacturers to approach for permission

| Manufacturer | Products | Contact |
| ------------ | -------- | ------- |
| Evermetal | Longspan, Metcoppo, corrugated, accessories | https://evermetal.ng |
| Tower Aluminium | Roofing profiles, ridge and flashing accessories | https://www.towerplc.com/towerroofings/accessories.php |
| Cilla Aluminium | Longspan, Metcopol, Steptiles | https://cillaaluminium.com/products.html |
| Ligcon Nigeria | Longspan, Metcoppo, Step Tiles | https://www.ligconnigeria.com.ng |

Note on terminology: manufacturers disagree on the spelling of the stepped
tile profile (Metcoppo, Metcopol, Step Tile). The business's preferred
spelling is **Metcoppo** and it is used consistently in the storefront.

## Before any photograph is published

1. Photograph the actual product, on a neutral background, 1600 × 1600 or larger.
2. Convert to WebP.
3. Write alt text that describes the specific product, not the category.
4. Record the source and permission in this register.
5. Upload through the admin panel so the image is served from Supabase Storage.
`;

writeFileSync("docs/image-assets.md", content);
console.log(`Wrote docs/image-assets.md (${assets.length} assets, ${pending.length} pending permission).`);